[manager]

prepend_keymap = [
	{ on = "i", run = "arrow -1", desc = "Move cursor up" },
	{ on = "k", run = "arrow 1",  desc = "Move cursor down" },
	{ on = "j", run = "leave", desc = "Go back to the parent directory" },
	{ on = "l", run = "enter", desc = "Enter the child directory" },
]
