alias git-prune="git branch --merged | egrep -v '(^\*|master|dev|production|test)' | xargs git branch -d" 
alias vt="set -Ux VAULT_TOKEN (vault login -method=oidc -token-only 2>/dev/null)"
alias vr="vault token renew $VAULT_TOKEN"
alias standup="git-standup -d 1 -a simone.cittadini && git-standup -d 1 -a franco.atzori && git-standup -d 1 -a dario.giarratana && git-standup -d 1 -a alfredo.guarnieri && git-standup -d 1 -a marco.robutti"
alias cdp="cd ~/workspace/pycc && code ."
alias cdpd="cd ~/workspace/pycc-dpe"
alias czc="git add -A . && cz commit"
alias cat="bat -p"